version: "3.1"
services: 
  db:
    container_name: postgres
    image: postgres:15.0
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /custom/mount:/var/lib/postgresql/data
    ports:
      - 5432
  redis:
    container_name: redis
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379
    volumes:
      - '/custom/redis:/data'

  app:
    container_name: app
    image: flask-smorest-api
    ports: 
      - 80:80 
    command: bash -c 'flask db upgrade && gunicorn --bind 0.0.0.0:80 "app:create_app()"'
    depends_on:
      - db
      - redis
    env_file:
      - .env

  worker:
    container_name: worker
    image: flask-smorest-api
    command: "rq worker -c settings"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app
